/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AppLocationSettingAutoscaling {
    /**
    * Indicates if autoscaling is enabled
    */
    'enabled': boolean;
    /**
    * Indicates if autoscaling health checks are enabled
    */
    'healthEnabled': boolean | null;
    /**
    * Grace period in seconds before failed health pings are counted
    */
    'healthInitialDelaySeconds': number | null;
    /**
    * Seconds between expected health pings
    */
    'healthPeriodSeconds': number | null;
    /**
    * Number of failed health pings before an instance is considered unhealthy
    */
    'healthFailureThreshold': number | null;
    /**
    * The minimum autoscaled instances
    */
    'minInstances': number | null;
    /**
    * The maximum autoscaled instances
    */
    'maxInstances': number | null;
    /**
    * Number of ready instances above allocated instances
    */
    'bufferSize': number | null;
    /**
    * The current number of autoscaled instances
    */
    'currentInstances': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "healthEnabled",
            "baseName": "healthEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "healthInitialDelaySeconds",
            "baseName": "healthInitialDelaySeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "healthPeriodSeconds",
            "baseName": "healthPeriodSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "healthFailureThreshold",
            "baseName": "healthFailureThreshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "minInstances",
            "baseName": "minInstances",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxInstances",
            "baseName": "maxInstances",
            "type": "number",
            "format": ""
        },
        {
            "name": "bufferSize",
            "baseName": "bufferSize",
            "type": "number",
            "format": ""
        },
        {
            "name": "currentInstances",
            "baseName": "currentInstances",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppLocationSettingAutoscaling.attributeTypeMap;
    }

    public constructor() {
    }
}
