/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckCapacityAppLocationSettingRequestPlacementConstraints } from '../models/CheckCapacityAppLocationSettingRequestPlacementConstraints.ts';
import { HttpFile } from '../http/http.ts';

/**
* The placement constraints that define the location
*/
export class CheckCapacityAppLocationSettingRequestPlacement {
    'constraints': CheckCapacityAppLocationSettingRequestPlacementConstraints;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "CheckCapacityAppLocationSettingRequestPlacementConstraints",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckCapacityAppLocationSettingRequestPlacement.attributeTypeMap;
    }

    public constructor() {
    }
}
