/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class DockerServiceDnsReachable {
    /**
    * The name for the port
    */
    'name': string;
    /**
    * Public URL over http
    */
    'dnsHttp': string | null;
    /**
    * Public URL over https
    */
    'dnsHttps': string | null;
    /**
    * Indicates whether the dnsHttp url is reachable
    */
    'dnsHttpReachable': boolean;
    /**
    * Indicates whether the dnsHttps url is reachable
    */
    'dnsHttpsReachable': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dnsHttp",
            "baseName": "dnsHttp",
            "type": "string",
            "format": ""
        },
        {
            "name": "dnsHttps",
            "baseName": "dnsHttps",
            "type": "string",
            "format": ""
        },
        {
            "name": "dnsHttpReachable",
            "baseName": "dnsHttpReachable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dnsHttpsReachable",
            "baseName": "dnsHttpsReachable",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DockerServiceDnsReachable.attributeTypeMap;
    }

    public constructor() {
    }
}
