/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DockerServiceAutoscalingStatus } from '../models/DockerServiceAutoscalingStatus.ts';
import { HttpFile } from '../http/http.ts';

export class DockerServiceAutoscaling {
    /**
    * Indicates if autoscaling is enabled
    */
    'enabled': boolean;
    /**
    * Indicates if autoscaling health checks are enabled
    */
    'healthEnabled': boolean | null;
    /**
    * The current autoscaling status.
    */
    'status': DockerServiceAutoscalingStatus | null;
    /**
    * The date/time the service was last flagged as ready.
    */
    'lastReadyAt': Date | null;
    /**
    * The date/time the service was last flagged as allocated.
    */
    'lastAllocatedAt': Date | null;
    /**
    * The date/time the service reported itself as healthy.
    */
    'lastHealthAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "healthEnabled",
            "baseName": "healthEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DockerServiceAutoscalingStatus",
            "format": ""
        },
        {
            "name": "lastReadyAt",
            "baseName": "lastReadyAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastAllocatedAt",
            "baseName": "lastAllocatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastHealthAt",
            "baseName": "lastHealthAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DockerServiceAutoscaling.attributeTypeMap;
    }

    public constructor() {
    }
}


