/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetAppLocationSettings200ResponseLinks } from '../models/GetAppLocationSettings200ResponseLinks.ts';
import { GetAppLocationSettings200ResponseMeta } from '../models/GetAppLocationSettings200ResponseMeta.ts';
import { Wallet } from '../models/Wallet.ts';
import { HttpFile } from '../http/http.ts';

export class GetAppWallets200Response {
    'data': Array<Wallet>;
    'links': GetAppLocationSettings200ResponseLinks;
    'meta': GetAppLocationSettings200ResponseMeta;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Wallet>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "GetAppLocationSettings200ResponseLinks",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "GetAppLocationSettings200ResponseMeta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAppWallets200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
