/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricInstantResult } from '../models/MetricInstantResult.ts';
import { HttpFile } from '../http/http.ts';

export class MetricInstantData {
    /**
    * The result type. For instant queries this will be \"vector\".
    */
    'resultType': string;
    /**
    * The vector data. Each entry represents one time series with its labels and current value.
    */
    'result': Array<MetricInstantResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resultType",
            "baseName": "resultType",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<MetricInstantResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricInstantData.attributeTypeMap;
    }

    public constructor() {
    }
}
