/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricTimeResult } from '../models/MetricTimeResult.ts';
import { HttpFile } from '../http/http.ts';

export class MetricData {
    /**
    * The result type. For range queries this will be \"matrix\".
    */
    'resultType': string;
    /**
    * The time series data. Each entry is one series with its labels and samples.
    */
    'result': Array<MetricTimeResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resultType",
            "baseName": "resultType",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<MetricTimeResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricData.attributeTypeMap;
    }

    public constructor() {
    }
}
