/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DnsMode } from '../models/DnsMode.ts';
import { Protocol } from '../models/Protocol.ts';
import { HttpFile } from '../http/http.ts';

export class PortDefinitionRequest {
    /**
    * The name of the server config
    */
    'name': string;
    /**
    * The protocols to expose
    */
    'protocols': Array<Protocol>;
    /**
    * The port to expose
    */
    'targetPort': number;
    /**
    * The DNS mode
    */
    'dnsMode'?: DnsMode | null;
    /**
    * Indicates if the port should be private (not publicly published)
    */
    'dnsPrivate'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "protocols",
            "baseName": "protocols",
            "type": "Array<Protocol>",
            "format": ""
        },
        {
            "name": "targetPort",
            "baseName": "targetPort",
            "type": "number",
            "format": ""
        },
        {
            "name": "dnsMode",
            "baseName": "dnsMode",
            "type": "DnsMode",
            "format": ""
        },
        {
            "name": "dnsPrivate",
            "baseName": "dnsPrivate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortDefinitionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


