/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class SteamBranch {
    /**
    * The name of the branch
    */
    'name': string;
    /**
    * The unique identifier for the build
    */
    'buildid': number | null;
    /**
    * Indicates whether a password is required
    */
    'pwdrequired': boolean | null;
    /**
    * A brief description of the build
    */
    'description': string | null;
    /**
    * Last updated timestamp (in Unix epoch format)
    */
    'timeupdated': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildid",
            "baseName": "buildid",
            "type": "number",
            "format": ""
        },
        {
            "name": "pwdrequired",
            "baseName": "pwdrequired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeupdated",
            "baseName": "timeupdated",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SteamBranch.attributeTypeMap;
    }

    public constructor() {
    }
}
