/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StoreOpenClawTemplateRequestApp } from '../models/StoreOpenClawTemplateRequestApp.ts';
import { StoreOpenClawTemplateRequestAppLocationSetting } from '../models/StoreOpenClawTemplateRequestAppLocationSetting.ts';
import { StoreOpenClawTemplateRequestPayment } from '../models/StoreOpenClawTemplateRequestPayment.ts';
import { StoreOpenClawTemplateRequestServerConfig } from '../models/StoreOpenClawTemplateRequestServerConfig.ts';
import { HttpFile } from '../http/http.ts';

export class StoreOpenClawTemplateRequest {
    'app'?: StoreOpenClawTemplateRequestApp;
    'serverConfig'?: StoreOpenClawTemplateRequestServerConfig;
    'appLocationSetting'?: StoreOpenClawTemplateRequestAppLocationSetting;
    'payment'?: StoreOpenClawTemplateRequestPayment;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "StoreOpenClawTemplateRequestApp",
            "format": ""
        },
        {
            "name": "serverConfig",
            "baseName": "serverConfig",
            "type": "StoreOpenClawTemplateRequestServerConfig",
            "format": ""
        },
        {
            "name": "appLocationSetting",
            "baseName": "appLocationSetting",
            "type": "StoreOpenClawTemplateRequestAppLocationSetting",
            "format": ""
        },
        {
            "name": "payment",
            "baseName": "payment",
            "type": "StoreOpenClawTemplateRequestPayment",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StoreOpenClawTemplateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
