/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateUpdatePlacement } from '../models/CreateUpdatePlacement.ts';
import { HttpFile } from '../http/http.ts';

export class StorePalworldTemplateRequest {
    /**
    * The name of the template app. If omitted, a default name will be used.
    */
    'appName'?: string | null;
    /**
    * The slug of the resource package. If omitted, a default resource package will be used.
    */
    'resourcePackageSlug'?: string | null;
    /**
    * The placement constraints that define the location. If omitted, no deployment will be created.
    */
    'placement'?: CreateUpdatePlacement | null;
    /**
    * Password required to deploy services to a protected location. Only required when the selected location is password-protected.
    */
    'password'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appName",
            "baseName": "appName",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourcePackageSlug",
            "baseName": "resourcePackageSlug",
            "type": "string",
            "format": ""
        },
        {
            "name": "placement",
            "baseName": "placement",
            "type": "CreateUpdatePlacement",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorePalworldTemplateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
