/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TemplateApp } from '../models/TemplateApp.ts';
import { TemplateAppLocationSetting } from '../models/TemplateAppLocationSetting.ts';
import { TemplateBinary } from '../models/TemplateBinary.ts';
import { TemplateServerConfig } from '../models/TemplateServerConfig.ts';
import { HttpFile } from '../http/http.ts';

export class TemplateAppResult {
    /**
    * The created template app
    */
    'app': TemplateApp;
    /**
    * The binaries created for this template app
    */
    'binaries': Array<TemplateBinary>;
    /**
    * The server configs created for this template app
    */
    'serverConfigs': Array<TemplateServerConfig>;
    /**
    * The app location settings created for this template app
    */
    'appLocationSettings': Array<TemplateAppLocationSetting>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "TemplateApp",
            "format": ""
        },
        {
            "name": "binaries",
            "baseName": "binaries",
            "type": "Array<TemplateBinary>",
            "format": ""
        },
        {
            "name": "serverConfigs",
            "baseName": "serverConfigs",
            "type": "Array<TemplateServerConfig>",
            "format": ""
        },
        {
            "name": "appLocationSettings",
            "baseName": "appLocationSettings",
            "type": "Array<TemplateAppLocationSetting>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateAppResult.attributeTypeMap;
    }

    public constructor() {
    }
}
