/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WalletCurrency } from '../models/WalletCurrency.ts';
import { WalletScope } from '../models/WalletScope.ts';
import { HttpFile } from '../http/http.ts';

export class Wallet {
    /**
    * The id of the wallet
    */
    'id': number;
    /**
    * The balance of the wallet
    */
    'balance': number;
    /**
    * The scope of the wallet.
    */
    'scope': WalletScope;
    /**
    * When the wallet was last updated
    */
    'updatedAt': Date;
    /**
    * The currency of the wallet
    */
    'currency': WalletCurrency;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "WalletScope",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "WalletCurrency",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Wallet.attributeTypeMap;
    }

    public constructor() {
    }
}


