/**
 * B2B_API
 * API to access 4Netplayers B2B platform empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type TierType = 'shared' | 'dedicated';

export const TierType = {
  Shared: 'shared' as TierType,
  Dedicated: 'dedicated' as TierType,
};
