/**
 * B2B_API
 * API to access 4Netplayers B2B platform empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceAllocations } from "../api/index.ts";
import { TierType } from './tier-type.ts';

/**
 * An object defining the resources of a server tier
 */
export interface Tier {
  /**
   * The id of the tier
   */
  id?: number;
  /**
   * The limits set for the server
   */
  resources?: ResourceAllocations;
  /**
   * The name of the tier
   */
  name?: string;
  /**
   * The price of the tier
   */
  price?: number;
  /**
   * The type of the tier
   */
  tierType?: TierType;
}
export namespace Tier {}
