/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BackupType } from "../models/BackupType.ts";
import { HttpFile } from "../http/http.ts";

export class Backup {
  /**
   * The name of the backup
   */
  "name": string;
  /**
   * The name of the stored archive
   */
  "archiveName": string;
  /**
   * The method of the archive
   */
  "backupMethod": BackupType;
  /**
   * The AWS region the backup is stored at
   */
  "awsRegion": string;
  /**
   * The timestamp of the backups creation
   */
  "createdAt": Date;
  /**
   * $restoredAt The timestamp of when the backup was restored, null if not restored
   */
  "restoredAt": Date | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": "",
    },
    {
      "name": "archiveName",
      "baseName": "archiveName",
      "type": "string",
      "format": "",
    },
    {
      "name": "backupMethod",
      "baseName": "backupMethod",
      "type": "BackupType",
      "format": "",
    },
    {
      "name": "awsRegion",
      "baseName": "awsRegion",
      "type": "string",
      "format": "",
    },
    {
      "name": "createdAt",
      "baseName": "createdAt",
      "type": "Date",
      "format": "date-time",
    },
    {
      "name": "restoredAt",
      "baseName": "restoredAt",
      "type": "Date",
      "format": "date-time",
    },
  ];

  static getAttributeTypeMap() {
    return Backup.attributeTypeMap;
  }

  public constructor() {
  }
}
