/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class ConfigTemplate {
  /**
   * The id of the config template
   */
  "id": string;
  /**
   * The binary id of the config template
   */
  "binaryId": string;
  /**
   * The name of the config template
   */
  "name": string;
  /**
   * The path in the container
   */
  "content": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "id",
      "baseName": "id",
      "type": "string",
      "format": "",
    },
    {
      "name": "binaryId",
      "baseName": "binaryId",
      "type": "string",
      "format": "",
    },
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": "",
    },
    {
      "name": "content",
      "baseName": "content",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return ConfigTemplate.attributeTypeMap;
  }

  public constructor() {
  }
}
