/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DockerRegistryType } from '../models/DockerRegistryType.ts';
import { HttpFile } from '../http/http.ts';

export class CreateDockerRegistryRequest {
    /**
    * The type of the docker registry
    */
    'type': DockerRegistryType;
    /**
    * The name of the docker registry
    */
    'name': string;
    /**
    * The URL of the docker registry
    */
    'url'?: string | null;
    /**
    * The URL of the gitlab instance
    */
    'instanceUrl'?: string | null;
    /**
    * The username to use for authentication
    */
    'username'?: string | null;
    /**
    * The access token to use for authentication
    */
    'accessToken'?: string | null;
    /**
    * The password to use for authentication
    */
    'password'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DockerRegistryType",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceUrl",
            "baseName": "instanceUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDockerRegistryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



