/**
 * B2B_API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class DockerImage {
    /**
    * The name of the docker image
    */
    'imageName': string;
    /**
    * The id of the registry to load the image
    */
    'registryId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "imageName",
            "baseName": "imageName",
            "type": "string",
            "format": ""
        },
        {
            "name": "registryId",
            "baseName": "registryId",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DockerImage.attributeTypeMap;
    }

    public constructor() {
    }
}

