/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DockerRegistryType } from "../models/DockerRegistryType.ts";
import { HttpFile } from "../http/http.ts";

export class DockerRegistry {
  /**
   * The ID of the registry
   */
  "id": number;
  /**
   * The type of the registry
   */
  "type": DockerRegistryType;
  /**
   * The name of the registry
   */
  "name": string;
  /**
   * The username to use for authentication
   */
  "username": string | null;
  /**
   * The password to use for authentication
   */
  "password": string | null;
  /**
   * The URL of the registry
   */
  "url": string;
  /**
   * The access token to use for authentication
   */
  "accessToken": string | null;
  /**
   * The URL of the instance
   */
  "instanceUrl": string | null;
  /**
   * Whether or not the registry is user-owned or organization-owned
   */
  "organization": boolean;
  /**
   * AWS access key ID
   */
  "awsAccessKey": string | null;
  /**
   * AWS secret access key
   */
  "awsSecretAccessKey": string | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "id",
      "baseName": "id",
      "type": "number",
      "format": "",
    },
    {
      "name": "type",
      "baseName": "type",
      "type": "DockerRegistryType",
      "format": "",
    },
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": "",
    },
    {
      "name": "username",
      "baseName": "username",
      "type": "string",
      "format": "",
    },
    {
      "name": "password",
      "baseName": "password",
      "type": "string",
      "format": "",
    },
    {
      "name": "url",
      "baseName": "url",
      "type": "string",
      "format": "uri",
    },
    {
      "name": "accessToken",
      "baseName": "accessToken",
      "type": "string",
      "format": "",
    },
    {
      "name": "instanceUrl",
      "baseName": "instanceUrl",
      "type": "string",
      "format": "uri",
    },
    {
      "name": "organization",
      "baseName": "organization",
      "type": "boolean",
      "format": "",
    },
    {
      "name": "awsAccessKey",
      "baseName": "awsAccessKey",
      "type": "string",
      "format": "",
    },
    {
      "name": "awsSecretAccessKey",
      "baseName": "awsSecretAccessKey",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return DockerRegistry.attributeTypeMap;
  }

  public constructor() {
  }
}
