/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class EnvironmentVariable {
  /**
   * The key of the environment variable
   */
  "key": string;
  /**
   * The value of the environment variable
   */
  "value": string | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "key",
      "baseName": "key",
      "type": "string",
      "format": "",
    },
    {
      "name": "value",
      "baseName": "value",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return EnvironmentVariable.attributeTypeMap;
  }

  public constructor() {
  }
}
