/**
 * B2B_API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnvironmentVariableType } from '../models/EnvironmentVariableType.ts';
import { HttpFile } from '../http/http.ts';

export class EnvironmentVariableDefinition {
    /**
    * The type of the environment variable
    */
    'type': EnvironmentVariableType;
    /**
    * The key of the variable
    */
    'key': string;
    /**
    * The value of the variable
    */
    'value'?: string;
    /**
    * The variable definition of the environment variable
    */
    'variable'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "EnvironmentVariableType",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "variable",
            "baseName": "variable",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentVariableDefinition.attributeTypeMap;
    }

    public constructor() {
    }
}



