/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class Location {
  /**
   * City
   */
  "city": string;
  /**
   * Continent
   */
  "continent": string;
  /**
   * Country
   */
  "country": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "city",
      "baseName": "city",
      "type": "string",
      "format": "",
    },
    {
      "name": "continent",
      "baseName": "continent",
      "type": "string",
      "format": "",
    },
    {
      "name": "country",
      "baseName": "country",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return Location.attributeTypeMap;
  }

  public constructor() {
  }
}
