/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export enum ServerConfigStatus {
    Pending = 'pending',
    Creating = 'creating',
    Updating = 'updating',
    Deleting = 'deleting',
    Error = 'error',
    Ready = 'ready'
}
