/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class SteamLauncher {
  /**
   * The executable path
   */
  "executable": string;
  /**
   * The arguments for the executable
   */
  "arguments": string | null;
  /**
   * The OS architecture of the executable
   */
  "osarch": string | null;
  /**
   * The OS of the executable
   */
  "oslist": string | null;
  /**
   * The realm of the executable
   */
  "realm": string | null;
  /**
   * The beta key of the executable
   */
  "betakey": string | null;
  /**
   * The description of the executable
   */
  "description": string | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "executable",
      "baseName": "executable",
      "type": "string",
      "format": "",
    },
    {
      "name": "arguments",
      "baseName": "arguments",
      "type": "string",
      "format": "",
    },
    {
      "name": "osarch",
      "baseName": "osarch",
      "type": "string",
      "format": "",
    },
    {
      "name": "oslist",
      "baseName": "oslist",
      "type": "string",
      "format": "",
    },
    {
      "name": "realm",
      "baseName": "realm",
      "type": "string",
      "format": "",
    },
    {
      "name": "betakey",
      "baseName": "betakey",
      "type": "string",
      "format": "",
    },
    {
      "name": "description",
      "baseName": "description",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return SteamLauncher.attributeTypeMap;
  }

  public constructor() {
  }
}
