/**
 * B2B_API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ZipFile {
    /**
    * The URL to the ZIP file
    */
    'zipFileUrl': string;
    /**
    * The command line to use
    */
    'commandLine': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "zipFileUrl",
            "baseName": "zipFileUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "commandLine",
            "baseName": "commandLine",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ZipFile.attributeTypeMap;
    }

    public constructor() {
    }
}

